### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Gloduck** [LanlingKira/key_style_right_click_menu#1]
萌新能请教一下如何应用到php的footer中么，万分感谢

**Comment by LanlingKira** [comment]
这是纯前端的，引入GalMenu.css、jquery.js、GalMenu.js这三个文件后
Html结构
```
<script type="text/javascript">
$(document).ready(function() {
    $("body").GalMenu({
        menu:"GalDropDown"
    });
    $(document).on("click", ".menuItem", function() {
        $(".circle").removeClass("open");
        $("#overlay").hide();
        $(".GalMenu").delay(400).hide(0);
    });
});
</script>
<div class="GalMenu GalDropDown">
  <div class="circle" id="gal">
    <div class="ring">
      <a href="#" title="Home" class="menuItem">Home</a>
      <a href="#" title="Blog" class="menuItem">Blog</a>
      <a href="#" title="About" class="menuItem">About</a>
      <a href="#" title="Contact" class="menuItem">Contact</a>
      <a href="#" title="Social" class="menuItem">Social</a>
      <a href="#" title="Other" class="menuItem">other</a></div>
  </div>
  <audio id="audio" src="audio/niconiconi.mp3"></audio>
</div> 
<div id="overlay" style="opacity: 1; cursor: pointer;"></div>
<script type="text/javascript">
var items = document.querySelectorAll(".menuItem");
for (var i = 0, l = items.length; i < l; i++) {
    items[i].style.left = (50 - 35 * Math.cos(-.5 * Math.PI - 2 * (1 / l) * i * Math.PI)).toFixed(4) + "%";
    items[i].style.top = (50 + 35 * Math.sin(-.5 * Math.PI - 2 * (1 / l) * i * Math.PI)).toFixed(4) + "%";
}
</script>

```
这是我以前写的，很乱，有空我重新整理一下

**Comment by Gloduck** [comment]
单个文件可以使用，但是引入到一个php程序就不行了，我想把这个引入到dz的footer中请问大概要引入到什么位置呢

**Comment by LanlingKira** [comment]
我已经重写了插件，修复了以前的一些错误，按照我写的文档使用就行了。
在php中混写html，写在php标记```<?php   ?>```之外就行了。
还有具体是什么错误导致无法使用？

**Comment by Gloduck** [comment]
嗯，好像是我顺序放错了，调换了一下顺序可以了。顺便问一下如果想要全局调用的话能否单独写一个php文件然后做引用呢

**Comment by LanlingKira** [comment]
可以这样做，也可以直接添加到dz模板里

**Comment by Gloduck** [comment]
这样写了要怎么引入呢，require和include引入到head或者body部分都无效,百度也没有明确的位置
![qq 20180107210439](https://user-images.githubusercontent.com/24894908/34649709-395d349a-f3ef-11e7-9f90-e45b32d8bcf3.png)

**Comment by LanlingKira** [comment]
以前的有些问题，代码已经更新，现在用我重写的`GalMenu.css`和`GalMenu.js`文件，在php里写
``` html
<link rel="stylesheet" type="text/css" href="css/GalMenu.css">
<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/GalMenu.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $("body").galMenu({
      menu:"galRing",
      click_to_close:true,
      stay_open:false
    });
  });
</script>
<div class="galMenu galRing">
  <div class="circle" id="gal">
    <div class="ring">
      <a href="#" title="Home" class="menuItem">Home</a>
      <a href="#" title="Blog" class="menuItem">Blog</a>
      <a href="#" title="About" class="menuItem">About</a>
      <a href="#" title="Contact" class="menuItem">Contact</a>
      <a href="#" title="Social" class="menuItem">Social</a>
      <a href="#" title="Other" class="menuItem">Other</a>
    </div>
    <audio id="galAudio" src="audio/nyanpass.mp3"></audio>
  </div>
</div>
<div id="overlay" style="opacity: 1; cursor: pointer;"></div>
```
这样就可以了。
如果已经引入过jquery文件，上述代码中的jquery.min.js文件就不需要再引入，并且php引入的位置需要在jquery文件引入之后，代码才能正确执行。

**Comment by Gloduck** [comment]
总感觉dz的footer无从下手

- [ ] 
![qq 20180107223129](https://user-images.githubusercontent.com/24894908/34650371-188e4306-f3fb-11e7-96b8-42f16399b86a.png)

**Comment by LanlingKira** [comment]
你的站点地址是什么，光看这图我也看不出来啊╮(￣▽￣)╭

**Comment by Gloduck** [comment]
唔。。。我先去研究研究，实在不行再来请教dalao。也不好意思耽误dalao太多时间

**Comment by Gloduck** [comment]
![qq 20180228020437](https://user-images.githubusercontent.com/24894908/36745944-0c7057b8-1c2c-11e8-9367-d9e2c3e2020a.png)
![qq 20180228020513](https://user-images.githubusercontent.com/24894908/36745945-0cb233ea-1c2c-11e8-9e7b-708b60ae0fa9.png)
现在能使用了，就是感觉有点不兼容，添加了过后字体会被默认放大，敢问dalao有解决办法么

**Comment by LanlingKira** [comment]
你直接使用了我的css吗？我给的样例里只有开头的body里面有设置字体大小。
为了避免冲突，你可以删掉开头html、body两行内容。
还有下面的 `a{text-decoration:none;outline:0}` ，我建议改成 `.ring a{text-decoration:none;outline:0}` 避免和其他样式冲突。
要是不行，你可以把网址发给我看看是什么问题。

**Comment by 1035311527** [comment]
已经完美解决，感谢大佬

**Comment by Gloduck** [comment]
好像这两个js有点冲突，引入如果引入两个的话第一个会被屏蔽，但是
如果只引入第二个的话那么鼠标右键貌似不能加载。能帮我看下么
![qq 20180228165702](https://user-images.githubusercontent.com/24894908/36778780-bc17166c-1ca8-11e8-8504-c0655eaaf751.png)
http://p1tk8ho58.bkt.clouddn.com/header.php

**Comment by LanlingKira** [comment]
具体哪两个，有对应控制台的错误消息吗

**Comment by Gloduck** [comment]
就图片中那个jq-1.83-min

**Comment by LanlingKira** [comment]
如果页面已经引入了jquery就不需要再引入。
GalMenu.js必须在jquery之后引入。

**Comment by Gloduck** [comment]
![qq 20180301202248](https://user-images.githubusercontent.com/24894908/36844815-28341926-1d8f-11e8-90ab-098d09025c47.png)
箭头是模板默认引入的jq，然后打圈的是加了过后的，但是貌似加载不出来，浏览器的话好像没有报错

**Comment by LanlingKira** [comment]
你把网址给我 我去看下 不然我也不知道什么问题

**Comment by Gloduck** [comment]
www.celes.com.cn   
您的插件可以加载，但是二级导航的jq就不兼容了，还有其他的也是
![qq 20180301212219](https://user-images.githubusercontent.com/24894908/36846720-b498b956-1d96-11e8-9ec0-e3640fc9da97.png)

![qq 20180301212050](https://user-images.githubusercontent.com/24894908/36846707-a7fee71a-1d96-11e8-9ac8-203756dc9137.png)

**Comment by LanlingKira** [comment]
抱歉，这两天有点忙。
网站打不开了_(:3」∠❀)_
